export default [
  {
    index: 0,
    property: 'ID',
    active: true
  }, {
    index: 1,
    property: 'Conditions',
    active: true,
    expanded: false,
    children: [{
      index: 0,
      property: 'TN1Z',
      active: true
    }, {
      index: 1,
      property: 'PTN',
      active: true
    }, {
      index: 2,
      property: 'ZIP',
      active: true
    }, {
      index: 3,
      property: 'MAXI',
      active: true
    }, {
      index: 4,
      property: 'TOTE',
      active: true
    }, {
      index: 5,
      property: 'Small',
      active: true
    }]
  }, {
    index: 2,
    property: 'Barcode',
    active: true,
    expanded: false,
    children: [{
      index: 0,
      property: 'TV',
      active: true
    }, {
      index: 1,
      property: 'TOPA',
      active: true
    }, {
      index: 2,
      property: 'LF',
      active: true
    }, {
      index: 3,
      property: 'RB',
      active: true
    }, {
      index: 4,
      property: 'RF',
      active: true
    }, {
      index: 5,
      property: 'LB',
      active: true
    }, {
      index: 6,
      property: 'BOT',
      active: true
    }]
  }, {
    index: 3,
    property: 'Dimensions',
    active: true,
    expanded: false,
    children: [{
      index: 0,
      property: 'L',
      active: true
    }, {
      index: 1,
      property: 'W',
      active: true
    }, {
      index: 2,
      property: 'H',
      active: true
    }, {
      index: 3,
      property: 'Gap',
      active: true
    }]
  }, {
    index: 4,
    property: 'UserFields',
    active: true,
    expanded: false,
    children: [{
      index: 0,
      property: 'STATUS',
      active: true
    }, {
      index: 1,
      property: 'NTEP',
      active: true
    }, {
      index: 2,
      property: 'DIM',
      active: true
    }, {
      index: 3,
      property: 'PLC',
      active: true
    }, {
      index: 4,
      property: 'PLC ID',
      active: true
    }]
  }, {
    index: 5,
    property: 'Host Message',
    active: true
  }
]
