export const tableConfig = {
  type: 'EventLog',
  name: 'EventLog',
  header: {
    tabs: [
      {
        index: 0,
        label: 'Event Log Table',
        isVisible: true,
        url: '',
        channel: '',
        columns: [
          {
            index: 0,
            property: 'column1',
            isVisible: true,
            isActive: true,
            width: 20,
            subcolumns: [],
            dataType: 'STRING',
            header: { label: 'Name' },
            sorting: false,
            sortingType: '',
            type: 'STRING',
            columnEditable: false,
            frontEndSort: false,
            sortAttribute: '',
          },
          {
            index: 1,
            property: 'column2',
            isVisible: true,
            isActive: true,
            width: 20,
            subcolumns: [],
            dataType: 'STRING',
            header: { label: 'Unique ID' },
            sorting: false,
            sortingType: '',
            type: 'STRING',
            columnEditable: false,
            frontEndSort: false,
            sortAttribute: '',
          },
          {
            index: 2,
            property: 'column3',
            isVisible: true,
            isActive: true,
            width: 20,
            subcolumns: [],
            dataType: 'DATETIME',
            header: { label: 'Date' },
            sorting: false,
            sortingType: '',
            type: 'STRING',
            columnEditable: false,
            frontEndSort: false,
            sortAttribute: '',
          },
          {
            index: 3,
            property: 'column4',
            isVisible: true,
            isActive: true,
            width: 20,
            subcolumns: [],
            dataType: 'STRING',
            header: { label: 'Status' },
            sorting: false,
            sortingType: '',
            type: 'STRING',
            columnEditable: false,
            frontEndSort: false,
            sortAttribute: '',
          },
          {
            index: 4,
            property: 'column5',
            isVisible: true,
            isActive: true,
            width: 20,
            subcolumns: [],
            dataType: 'STRING',
            header: { label: 'Note' },
            sorting: false,
            sortingType: '',
            type: 'STRING',
            columnEditable: false,
            frontEndSort: false,
            sortAttribute: '',
          },
        ],
        resizable: false,
        expanded: false,
        defaultColumn: { index: 0, property: 'column1' },
        pagination: false,
        paginationFrontEnd: false,
        sortColumn: '',
        sortDirection: '',
      },
    ],
  },
  operations: [{ type: 'icon', icon: 'download', isVisible: true, filter: [''], value: '' }],
  tip: { label: '', icon: '', isVisible: false, timer: 10 },
  tableTimer: 10,
};

export const tableRows = {
  id: '629795c9-dee0-4465-b454-f86391b1a714',
  rows: [
    {
      rowId: '9d7add85-042f-440c-9a1d-d0a479151d8a',
      rowName: 'Door6 Non Contact',
      canEdit: true,
      canDelete: true,
      columnData: [
        {
          id: 'column1',
          cellData: {
            id: 'CellData1',
            dataType: 'STRING',
            type: 'STRING',
            value: ['Wrapper infeed Lc'],
            colorName: 'Grey',
            colorValue: 500,
            href: null,
            metaData: null,
            level: null,
            frontEndSort: true,
            sortAttribute: '',
            date: null,
          },
          hasSubColumns: false,
          subColumnData: null,
        },
        {
          id: 'column2',
          cellData: {
            id: 'CellData2',
            dataType: 'STRING',
            type: 'STRING',
            value: ['LC214'],
            colorName: 'Grey',
            colorValue: 500,
            href: null,
            metaData: null,
            level: null,
            frontEndSort: true,
            sortAttribute: '',
            date: null,
          },
          hasSubColumns: false,
          subColumnData: null,
        },
        {
          id: 'column3',
          cellData: {
            id: 'CellData3',
            dataType: 'STRING',
            type: 'STRING',
            value: ['26 June 2018  12:06:53 PM'],
            colorName: 'Grey',
            colorValue: 500,
            href: null,
            metaData: null,
            level: null,
            frontEndSort: true,
            sortAttribute: '',
            date: null,
          },
          hasSubColumns: null,
          subColumnData: null,
        },
        {
          id: 'column4',
          cellData: {
            id: 'CellData4',
            dataType: 'STRING',
            type: 'STRING',
            value: ['Switch Closed'],
            colorName: 'Grey',
            colorValue: 500,
            href: null,
            metaData: null,
            level: null,
            frontEndSort: true,
            sortAttribute: '',
            date: null,
          },
          hasSubColumns: null,
          subColumnData: null,
        },
        {
          id: 'column5',
          cellData: {
            id: 'CellData5',
            dataType: 'STRING',
            type: 'PARAGRAPH',
            value: [''],
            colorName: 'Grey',
            colorValue: 500,
            href: null,
            metaData: null,
            level: null,
            frontEndSort: true,
            sortAttribute: '',
            date: null,
          },
          hasSubColumns: null,
          subColumnData: null,
        },
      ],
      isChartOpen: null,
      canCollapseDown: null,
      isEditEnable: true,
      isDeleteEnable: true,
      isChartEnable: true,
    },
    {
      rowId: '9d7add85-042f-440c-9a1d-d0a479151d8a',
      rowName: 'Door6 Non Contact',
      canEdit: true,
      canDelete: true,
      columnData: [
        {
          id: 'column1',
          cellData: {
            id: 'CellData1',
            dataType: 'STRING',
            type: 'STRING',
            value: ['Wrapper Infeed Lc '],
            colorName: 'Grey',
            colorValue: 500,
            href: null,
            metaData: null,
            level: null,
            frontEndSort: true,
            sortAttribute: '',
            date: null,
          },
          hasSubColumns: false,
          subColumnData: null,
        },
        {
          id: 'column2',
          cellData: {
            id: 'CellData2',
            dataType: 'STRING',
            type: 'STRING',
            value: ['Lc215'],
            colorName: 'Grey',
            colorValue: 500,
            href: null,
            metaData: null,
            level: null,
            frontEndSort: true,
            sortAttribute: '',
            date: null,
          },
          hasSubColumns: false,
          subColumnData: null,
        },
        {
          id: 'column3',
          cellData: {
            id: 'CellData3',
            dataType: 'STRING',
            type: 'STRING',
            value: ['26 June 2018  12:06:53 PM'],
            colorName: 'Grey',
            colorValue: 500,
            href: null,
            metaData: null,
            level: null,
            frontEndSort: true,
            sortAttribute: '',
            date: null,
          },
          hasSubColumns: null,
          subColumnData: null,
        },
        {
          id: 'column4',
          cellData: {
            id: 'CellData4',
            dataType: 'STRING',
            type: 'STRING',
            value: ['Switch Closed'],
            colorName: 'Grey',
            colorValue: 500,
            href: null,
            metaData: null,
            level: null,
            frontEndSort: true,
            sortAttribute: '',
            date: null,
          },
          hasSubColumns: null,
          subColumnData: null,
        },
        {
          id: 'column5',
          cellData: {
            id: 'CellData5',
            dataType: 'STRING',
            type: 'PARAGRAPH',
            value: ['Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor inc'],
            colorName: 'Grey',
            colorValue: 500,
            href: null,
            metaData: null,
            level: null,
            frontEndSort: true,
            sortAttribute: '',
            date: null,
          },
          hasSubColumns: null,
          subColumnData: null,
        },
      ],
      isChartOpen: null,
      canCollapseDown: null,
      isEditEnable: true,
      isDeleteEnable: true,
      isChartEnable: true,
    },
    {
      rowId: '9d7add85-042f-440c-9a1d-d0a479151d8a',
      rowName: 'Door6 Non Contact',
      canEdit: true,
      canDelete: true,
      columnData: [
        {
          id: 'column1',
          cellData: {
            id: 'CellData1',
            dataType: 'STRING',
            type: 'STRING',
            value: ['Wrapper Arm Infeed lc'],
            colorName: 'Grey',
            colorValue: 500,
            href: null,
            metaData: null,
            level: null,
            frontEndSort: true,
            sortAttribute: '',
            date: null,
          },
          hasSubColumns: false,
          subColumnData: null,
        },
        {
          id: 'column2',
          cellData: {
            id: 'CellData2',
            dataType: 'STRING',
            type: 'STRING',
            value: ['Lc216'],
            colorName: 'Grey',
            colorValue: 500,
            href: null,
            metaData: null,
            level: null,
            frontEndSort: true,
            sortAttribute: '',
            date: null,
          },
          hasSubColumns: false,
          subColumnData: null,
        },
        {
          id: 'column3',
          cellData: {
            id: 'CellData3',
            dataType: 'STRING',
            type: 'STRING',
            value: ['26 June 2018  12:06:53 PM'],
            colorName: 'Grey',
            colorValue: 500,
            href: null,
            metaData: null,
            level: null,
            frontEndSort: true,
            sortAttribute: '',
            date: null,
          },
          hasSubColumns: null,
          subColumnData: null,
        },
        {
          id: 'column4',
          cellData: {
            id: 'CellData4',
            dataType: 'STRING',
            type: 'STRING',
            value: ['Switch Closed'],
            colorName: 'Grey',
            colorValue: 500,
            href: null,
            metaData: null,
            level: null,
            frontEndSort: true,
            sortAttribute: '',
            date: null,
          },
          hasSubColumns: null,
          subColumnData: null,
        },
        {
          id: 'column5',
          cellData: {
            id: 'CellData5',
            dataType: 'STRING',
            type: 'PARAGRAPH',
            value: ['Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor inc'],
            colorName: 'Grey',
            colorValue: 500,
            href: null,
            metaData: null,
            level: null,
            frontEndSort: true,
            sortAttribute: '',
            date: null,
          },
          hasSubColumns: null,
          subColumnData: null,
        },
      ],
      isChartOpen: null,
      canCollapseDown: null,
      isEditEnable: true,
      isDeleteEnable: true,
      isChartEnable: true,
    },
    {
      rowId: '9d7add85-042f-440c-9a1d-d0a479151d8a',
      rowName: 'Door6 Non Contact',
      canEdit: true,
      canDelete: true,
      columnData: [
        {
          id: 'column1',
          cellData: {
            id: 'CellData1',
            dataType: 'STRING',
            type: 'STRING',
            value: ['Wrapper Infeed Lc'],
            colorName: 'Grey',
            colorValue: 500,
            href: null,
            metaData: null,
            level: null,
            frontEndSort: true,
            sortAttribute: '',
            date: null,
          },
          hasSubColumns: false,
          subColumnData: null,
        },
        {
          id: 'column2',
          cellData: {
            id: 'CellData2',
            dataType: 'STRING',
            type: 'STRING',
            value: ['Lc217'],
            colorName: 'Grey',
            colorValue: 500,
            href: null,
            metaData: null,
            level: null,
            frontEndSort: true,
            sortAttribute: '',
            date: null,
          },
          hasSubColumns: false,
          subColumnData: null,
        },
        {
          id: 'column3',
          cellData: {
            id: 'CellData3',
            dataType: 'STRING',
            type: 'STRING',
            value: ['26 June 2018  12:06:53 PM'],
            colorName: 'Grey',
            colorValue: 500,
            href: null,
            metaData: null,
            level: null,
            frontEndSort: true,
            sortAttribute: '',
            date: null,
          },
          hasSubColumns: null,
          subColumnData: null,
        },
        {
          id: 'column4',
          cellData: {
            id: 'CellData4',
            dataType: 'STRING',
            type: 'STRING',
            value: ['Switch Closed'],
            colorName: 'Grey',
            colorValue: 500,
            href: null,
            metaData: null,
            level: null,
            frontEndSort: true,
            sortAttribute: '',
            date: null,
          },
          hasSubColumns: null,
          subColumnData: null,
        },
        {
          id: 'column5',
          cellData: {
            id: 'CellData5',
            dataType: 'STRING',
            type: 'PARAGRAPH',
            value: ['Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor inc'],
            colorName: 'Grey',
            colorValue: 500,
            href: null,
            metaData: null,
            level: null,
            frontEndSort: true,
            sortAttribute: '',
            date: null,
          },
          hasSubColumns: null,
          subColumnData: null,
        },
      ],
      isChartOpen: null,
      canCollapseDown: null,
      isEditEnable: true,
      isDeleteEnable: true,
      isChartEnable: true,
    },
  ],
  rowCount: null,
  name: 'Wrapper Arm 2',
  isActive: true,
};
