const TEMP = [
  {
    subCondition: [
      {
        code: 'startDate',
        label: 'Start Date',
        placeholders: ['Select Date', 'Select Time'],
        unit: '',
        dataType: 'DATETIME',
        type: 'DATE',
        required: true,
        isVisible: true,
      },
      {
        code: 'endDate',
        label: 'End Date ',
        placeholders: ['Select Date', 'Select Time'],
        unit: '',
        dataType: 'DATETIME',
        type: 'DATE',
        required: true,
        isVisible: true,
      },
      // {
      //   code: 'today',
      //   label: 'Today',
      //   placeholders: [],
      //   unit: '',
      //   dataType: 'STRING',
      //   type: 'BUTTON',
      //   required: true,
      //   isVisible: true,
      // },
      // {
      //   code: 'week',
      //   label: 'This Week',
      //   placeholders: [],
      //   unit: '',
      //   dataType: 'STRING',
      //   type: 'BUTTON',
      //   required: true,
      //   isVisible: true,
      // },
      // {
      //   code: 'month',
      //   label: 'This Month',
      //   placeholders: [],
      //   unit: '',
      //   dataType: 'STRING',
      //   type: 'BUTTON',
      //   required: true,
      //   isVisible: true,
      // },
      {
        code: 'yesterday',
        label: 'Yesterday',
        placeholders: [],
        unit: '',
        dataType: 'STRING',
        type: 'BUTTON',
        required: true,
        isVisible: true,
      },
      {
        code: '7days',
        label: 'Last 7 days',
        placeholders: [],
        unit: '',
        dataType: 'STRING',
        type: 'BUTTON',
        required: true,
        isVisible: true,
      },
      {
        code: '30days',
        label: 'Last 30 days',
        placeholders: [],
        unit: '',
        dataType: 'STRING',
        type: 'BUTTON',
        required: true,
        isVisible: true,
      },
      {
        code: '90days',
        label: 'Last 90 days',
        placeholders: [],
        unit: '',
        dataType: 'STRING',
        type: 'BUTTON',
        required: true,
        isVisible: true,
      },
    ],
  },
];

export default TEMP;
